# Generated by Django 2.2 on 2022-01-03 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jay_bhairav_enterprice_app', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(default='', null=True, upload_to='Images/')),
                ('img2', models.ImageField(default='', null=True, upload_to='Images/')),
                ('img3', models.ImageField(default='', null=True, upload_to='Images/')),
                ('img4', models.ImageField(default='', null=True, upload_to='Images/')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jay_bhairav_enterprice_app.Category')),
            ],
        ),
    ]
