# Generated by Django 2.2 on 2022-01-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jay_bhairav_enterprice_app', '0004_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='Call_For_Price',
            field=models.CharField(default='No', max_length=5),
        ),
        migrations.AddField(
            model_name='product_details',
            name='Country_Of_Manufacture',
            field=models.CharField(default='India', max_length=20),
        ),
    ]
