# Generated by Django 2.2 on 2022-01-04 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jay_bhairav_enterprice_app', '0006_auto_20220104_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Name',
            new_name='Category_Name',
        ),
    ]
