# Generated by Django 2.2 on 2022-01-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jay_bhairav_enterprice_app', '0007_auto_20220104_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
