# Generated by Django 2.2 on 2022-01-04 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jay_bhairav_enterprice_app', '0008_newsletter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newsletter',
            new_name='Subscribe',
        ),
    ]
