# Generated by Django 2.2 on 2022-01-04 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jay_bhairav_enterprice_app', '0009_auto_20220104_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='img',
            new_name='Img',
        ),
    ]
