# Generated by Django 2.2 on 2022-01-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jay_bhairav_enterprice_app', '0011_auto_20220105_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('File', models.FileField(default='Abc.pdf', upload_to='files/')),
            ],
        ),
    ]
